CREATE TABLE houses (
    id NUMBER PRIMARY KEY,
    sale_date DATE,
    price NUMBER,
    bedrooms NUMBER,
    bathrooms NUMBER,
    sqft_living NUMBER,
    sqft_lot NUMBER,
    floors NUMBER,
    waterfront NUMBER,
    house_view NUMBER,
    house_condition NUMBER,
    grade NUMBER,
    sqft_above NUMBER,
    sqft_basement NUMBER,
    yr_built NUMBER,
    yr_renovated NUMBER,
    zipcode VARCHAR2(10),
    latitude NUMBER,
    longitude NUMBER,
    sqft_living15 NUMBER,
    sqft_lot15 NUMBER
);

GRANT ALL ON houses TO krejnerw;

CREATE TABLE houses_archive AS SELECT * FROM houses WHERE 1=0;
ALTER TABLE houses_archive
ADD (deleted_by VARCHAR2(100) DEFAULT 'UNKNOWN' NOT NULL,
     deleted_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL);
GRANT ALL ON houses_archive TO krejnerw;

CREATE TABLE houses_log
(
    log_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_date       TIMESTAMP DEFAULT SYSTIMESTAMP,
    operation_type VARCHAR2(20),
    record_id      NUMBER,
    user_name      VARCHAR2(30),
    old_values CLOB,
    new_values CLOB
);

GRANT ALL ON houses_log TO krejnerw;

CREATE TABLE monthly_summary (
    year NUMBER,
    month NUMBER,
    total_sales NUMBER,
    total_revenue NUMBER,
    average_price NUMBER,
    PRIMARY KEY (year, month)
);

GRANT ALL ON monthly_summary TO krejnerw;

CREATE TABLE quarterly_summary (
    year NUMBER,
    quarter NUMBER,
    total_sales NUMBER,
    total_revenue NUMBER,
    average_price NUMBER,
    PRIMARY KEY (year, quarter)
);

GRANT ALL ON quarterly_summary TO krejnerw;

CREATE TABLE yearly_summary (
    year NUMBER,
    total_sales NUMBER,
    total_revenue NUMBER,
    average_price NUMBER,
    PRIMARY KEY (year)
);

GRANT ALL ON yearly_summary TO krejnerw;
